// Featured roles curated from MyWorld Careers (myworld.com.mm).
// These are public listings shown as external opportunities alongside our own.

export type ExternalJob = {
  id: string;
  title: string;
  company: string;
  location: string;
  city: "Yangon" | "Mandalay" | "Nay Pyi Taw" | "Remote";
  job_type: "full_time" | "part_time" | "contract" | "internship" | "remote";
  function: string; // Sales, Engineering, Finance, etc.
  industry: string;
  salary_min: number | null;
  salary_max: number | null;
  salary_currency: "MMK" | "USD";
  skills: string[];
  description: string;
  source: "MyWorld Careers";
  source_url: string;
  posted_days_ago: number;
};

const MW = "https://www.myworld.com.mm/jobs";

export const MYWORLD_JOBS: ExternalJob[] = [
  {
    id: "mw-001",
    title: "Sales Manager (FMCG)",
    company: "Leading FMCG Distributor",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Sales & Business Development",
    industry: "FMCG",
    salary_min: 2_500_000, salary_max: 4_000_000, salary_currency: "MMK",
    skills: ["Sales", "Channel Management", "Team Leadership", "FMCG"],
    description: "Drive nationwide sales for a top FMCG brand. Lead a team of 15+ across modern trade and general trade channels.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 3,
  },
  {
    id: "mw-002",
    title: "Finance Manager",
    company: "International Bank (Yangon Branch)",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Finance & Accounting",
    industry: "Banking",
    salary_min: 3_500_000, salary_max: 5_500_000, salary_currency: "MMK",
    skills: ["IFRS", "Reporting", "Budgeting", "ACCA"],
    description: "Lead financial reporting and budgeting for the Myanmar branch of a regional bank. ACCA / CPA preferred.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 5,
  },
  {
    id: "mw-003",
    title: "HR Business Partner",
    company: "Manufacturing Group",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Human Resources",
    industry: "Manufacturing",
    salary_min: 2_000_000, salary_max: 3_200_000, salary_currency: "MMK",
    skills: ["HRBP", "Employee Relations", "Talent", "Labour Law"],
    description: "Partner with plant leadership on talent, performance and engagement across 800+ employees.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 1,
  },
  {
    id: "mw-004",
    title: "Marketing Manager",
    company: "Consumer Electronics Brand",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Marketing",
    industry: "Retail / Consumer",
    salary_min: 2_800_000, salary_max: 4_500_000, salary_currency: "MMK",
    skills: ["Brand", "Digital Marketing", "Campaigns", "Budget"],
    description: "Own brand strategy, ATL/BTL campaigns, and digital growth for a fast-growing consumer electronics brand.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 6,
  },
  {
    id: "mw-005",
    title: "Software Engineer (Backend)",
    company: "Regional Fintech",
    location: "Yangon, Myanmar (Hybrid)",
    city: "Yangon",
    job_type: "full_time",
    function: "Technology",
    industry: "Fintech",
    salary_min: 2_500_000, salary_max: 4_500_000, salary_currency: "MMK",
    skills: ["Node.js", "PostgreSQL", "AWS", "REST APIs"],
    description: "Build and scale payment APIs serving banks and merchants across Southeast Asia.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 2,
  },
  {
    id: "mw-006",
    title: "Plant Manager",
    company: "Food Manufacturing Plc.",
    location: "Mandalay, Myanmar",
    city: "Mandalay",
    job_type: "full_time",
    function: "Operations",
    industry: "Food & Beverage",
    salary_min: 3_500_000, salary_max: 5_500_000, salary_currency: "MMK",
    skills: ["Lean", "ISO 22000", "Production Planning", "Leadership"],
    description: "Run a 24/7 food production plant in Mandalay. Drive efficiency, food safety and team development.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 8,
  },
  {
    id: "mw-007",
    title: "Country Manager",
    company: "Logistics Multinational",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Executive",
    industry: "Logistics",
    salary_min: 6_000_000, salary_max: 10_000_000, salary_currency: "MMK",
    skills: ["P&L", "Strategy", "Stakeholders", "Logistics"],
    description: "Lead Myanmar operations for a global freight forwarder. P&L ownership, government and client relationships.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 4,
  },
  {
    id: "mw-008",
    title: "Sales Executive (Pharma)",
    company: "Multinational Pharma",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Sales",
    industry: "Pharmaceutical",
    salary_min: 900_000, salary_max: 1_500_000, salary_currency: "MMK",
    skills: ["Medical Sales", "Doctor Calls", "Reporting"],
    description: "Promote prescription products to hospitals and clinics in Yangon. Great entry role for life-science graduates.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 1,
  },
  {
    id: "mw-009",
    title: "Internal Auditor",
    company: "Conglomerate",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Audit & Risk",
    industry: "Conglomerate",
    salary_min: 1_800_000, salary_max: 2_800_000, salary_currency: "MMK",
    skills: ["Internal Audit", "Risk", "SOX", "CIA"],
    description: "Plan and execute risk-based internal audits across SBUs. CIA part-qualified welcome.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 9,
  },
  {
    id: "mw-010",
    title: "Procurement Specialist",
    company: "NGO / International",
    location: "Nay Pyi Taw, Myanmar",
    city: "Nay Pyi Taw",
    job_type: "contract",
    function: "Supply Chain",
    industry: "Non-profit",
    salary_min: 1_400_000, salary_max: 2_200_000, salary_currency: "MMK",
    skills: ["Tenders", "Vendor Mgmt", "Donor Compliance"],
    description: "12-month contract supporting humanitarian procurement under donor compliance rules.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 7,
  },
  {
    id: "mw-011",
    title: "Digital Marketing Executive",
    company: "E-commerce Startup",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Marketing",
    industry: "E-commerce",
    salary_min: 800_000, salary_max: 1_400_000, salary_currency: "MMK",
    skills: ["Meta Ads", "Google Ads", "Analytics", "Content"],
    description: "Plan and run paid social and search campaigns. Report on CAC, ROAS and growth experiments.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 2,
  },
  {
    id: "mw-012",
    title: "Civil Engineer",
    company: "Property Developer",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Engineering",
    industry: "Construction",
    salary_min: 1_500_000, salary_max: 2_500_000, salary_currency: "MMK",
    skills: ["Site Supervision", "AutoCAD", "QA/QC"],
    description: "Supervise high-rise residential projects. Coordinate with consultants and contractors on quality and schedule.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 6,
  },
  {
    id: "mw-013",
    title: "Operations Intern",
    company: "International Trading Co.",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "internship",
    function: "Operations",
    industry: "Trading",
    salary_min: 300_000, salary_max: 500_000, salary_currency: "MMK",
    skills: ["Excel", "Logistics", "Communication"],
    description: "6-month paid internship supporting order processing, shipment tracking and supplier follow-ups.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 1,
  },
  {
    id: "mw-014",
    title: "Customer Service Representative (Remote)",
    company: "BPO — Regional",
    location: "Remote — Myanmar",
    city: "Remote",
    job_type: "remote",
    function: "Customer Service",
    industry: "BPO",
    salary_min: 700_000, salary_max: 1_100_000, salary_currency: "MMK",
    skills: ["English", "Chat Support", "CRM"],
    description: "Handle English-language chat and email support for SaaS customers. Rotational shifts.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 3,
  },
  {
    id: "mw-015",
    title: "Brand Manager (Beauty)",
    company: "Personal Care Multinational",
    location: "Yangon, Myanmar",
    city: "Yangon",
    job_type: "full_time",
    function: "Marketing",
    industry: "Beauty / Personal Care",
    salary_min: 3_000_000, salary_max: 4_800_000, salary_currency: "MMK",
    skills: ["Brand Strategy", "Innovation", "Insights"],
    description: "Own a hero skincare brand in Myanmar. Drive innovation funnel, comms strategy and category share.",
    source: "MyWorld Careers", source_url: MW, posted_days_ago: 10,
  },
];

export type MyWorldCity = ExternalJob["city"];
export const MYWORLD_CITIES: MyWorldCity[] = ["Yangon", "Mandalay", "Nay Pyi Taw", "Remote"];
