/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GraduatesRouteImport } from './routes/graduates'
import { Route as FindPassionRouteImport } from './routes/find-passion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraduatesIndexRouteImport } from './routes/graduates.index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GraduatesProfileRouteImport } from './routes/graduates.profile'
import { Route as GraduatesMessagingRouteImport } from './routes/graduates.messaging'
import { Route as GraduatesCvAnalyzerRouteImport } from './routes/graduates.cv-analyzer'
import { Route as CandidatesRecruiterDashboardRouteImport } from './routes/candidates.recruiter-dashboard'
import { Route as CandidatesFeaturesRouteImport } from './routes/candidates.features'
import { Route as CandidatesBrowseRouteImport } from './routes/candidates.browse'
import { Route as AuthenticatedUnauthorizedRouteImport } from './routes/_authenticated/unauthorized'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student.index'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedStudentMyCvRouteImport } from './routes/_authenticated/student.my-cv'
import { Route as AuthenticatedStudentMessagesRouteImport } from './routes/_authenticated/student.messages'
import { Route as AuthenticatedStudentLearnRouteImport } from './routes/_authenticated/student.learn'
import { Route as AuthenticatedStudentJobMapRouteImport } from './routes/_authenticated/student.job-map'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student.dashboard'
import { Route as AuthenticatedStudentCvAnalyzerRouteImport } from './routes/_authenticated/student.cv-analyzer'
import { Route as AuthenticatedStudentApplicationsRouteImport } from './routes/_authenticated/student.applications'
import { Route as AuthenticatedEmployerMessagesRouteImport } from './routes/_authenticated/employer.messages'
import { Route as AuthenticatedEmployerDashboardRouteImport } from './routes/_authenticated/employer.dashboard'
import { Route as AuthenticatedEmployerCvBoardRouteImport } from './routes/_authenticated/employer.cv-board'
import { Route as AuthenticatedEmployerApplicationsRouteImport } from './routes/_authenticated/employer.applications'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedStudentJobsIndexRouteImport } from './routes/_authenticated/student.jobs.index'
import { Route as AuthenticatedEmployerJobsIndexRouteImport } from './routes/_authenticated/employer.jobs.index'
import { Route as AuthenticatedStudentJobsJobIdRouteImport } from './routes/_authenticated/student.jobs.$jobId'
import { Route as AuthenticatedEmployerJobsNewRouteImport } from './routes/_authenticated/employer.jobs.new'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesRoute = GraduatesRouteImport.update({
  id: '/graduates',
  path: '/graduates',
  getParentRoute: () => rootRouteImport,
} as any)
const FindPassionRoute = FindPassionRouteImport.update({
  id: '/find-passion',
  path: '/find-passion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesIndexRoute = GraduatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GraduatesRoute,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidatesRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const GraduatesProfileRoute = GraduatesProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GraduatesRoute,
} as any)
const GraduatesMessagingRoute = GraduatesMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => GraduatesRoute,
} as any)
const GraduatesCvAnalyzerRoute = GraduatesCvAnalyzerRouteImport.update({
  id: '/cv-analyzer',
  path: '/cv-analyzer',
  getParentRoute: () => GraduatesRoute,
} as any)
const CandidatesRecruiterDashboardRoute =
  CandidatesRecruiterDashboardRouteImport.update({
    id: '/recruiter-dashboard',
    path: '/recruiter-dashboard',
    getParentRoute: () => CandidatesRoute,
  } as any)
const CandidatesFeaturesRoute = CandidatesFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => CandidatesRoute,
} as any)
const CandidatesBrowseRoute = CandidatesBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => CandidatesRoute,
} as any)
const AuthenticatedUnauthorizedRoute =
  AuthenticatedUnauthorizedRouteImport.update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStudentMyCvRoute =
  AuthenticatedStudentMyCvRouteImport.update({
    id: '/my-cv',
    path: '/my-cv',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentMessagesRoute =
  AuthenticatedStudentMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentLearnRoute =
  AuthenticatedStudentLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentJobMapRoute =
  AuthenticatedStudentJobMapRouteImport.update({
    id: '/job-map',
    path: '/job-map',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentCvAnalyzerRoute =
  AuthenticatedStudentCvAnalyzerRouteImport.update({
    id: '/cv-analyzer',
    path: '/cv-analyzer',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentApplicationsRoute =
  AuthenticatedStudentApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedEmployerMessagesRoute =
  AuthenticatedEmployerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerDashboardRoute =
  AuthenticatedEmployerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerCvBoardRoute =
  AuthenticatedEmployerCvBoardRouteImport.update({
    id: '/cv-board',
    path: '/cv-board',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerApplicationsRoute =
  AuthenticatedEmployerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStudentJobsIndexRoute =
  AuthenticatedStudentJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedEmployerJobsIndexRoute =
  AuthenticatedEmployerJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedStudentJobsJobIdRoute =
  AuthenticatedStudentJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedEmployerJobsNewRoute =
  AuthenticatedEmployerJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/contact': typeof ContactRoute
  '/find-passion': typeof FindPassionRoute
  '/graduates': typeof GraduatesRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/candidates/browse': typeof CandidatesBrowseRoute
  '/candidates/features': typeof CandidatesFeaturesRoute
  '/candidates/recruiter-dashboard': typeof CandidatesRecruiterDashboardRoute
  '/graduates/cv-analyzer': typeof GraduatesCvAnalyzerRoute
  '/graduates/messaging': typeof GraduatesMessagingRoute
  '/graduates/profile': typeof GraduatesProfileRoute
  '/news/$slug': typeof NewsSlugRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/graduates/': typeof GraduatesIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/employer/cv-board': typeof AuthenticatedEmployerCvBoardRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/cv-analyzer': typeof AuthenticatedStudentCvAnalyzerRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/job-map': typeof AuthenticatedStudentJobMapRoute
  '/student/learn': typeof AuthenticatedStudentLearnRoute
  '/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/student/my-cv': typeof AuthenticatedStudentMyCvRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/student/jobs/$jobId': typeof AuthenticatedStudentJobsJobIdRoute
  '/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/student/jobs/': typeof AuthenticatedStudentJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/find-passion': typeof FindPassionRoute
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/candidates/browse': typeof CandidatesBrowseRoute
  '/candidates/features': typeof CandidatesFeaturesRoute
  '/candidates/recruiter-dashboard': typeof CandidatesRecruiterDashboardRoute
  '/graduates/cv-analyzer': typeof GraduatesCvAnalyzerRoute
  '/graduates/messaging': typeof GraduatesMessagingRoute
  '/graduates/profile': typeof GraduatesProfileRoute
  '/news/$slug': typeof NewsSlugRoute
  '/candidates': typeof CandidatesIndexRoute
  '/graduates': typeof GraduatesIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/employer/cv-board': typeof AuthenticatedEmployerCvBoardRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/cv-analyzer': typeof AuthenticatedStudentCvAnalyzerRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/job-map': typeof AuthenticatedStudentJobMapRoute
  '/student/learn': typeof AuthenticatedStudentLearnRoute
  '/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/student/my-cv': typeof AuthenticatedStudentMyCvRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/student/jobs/$jobId': typeof AuthenticatedStudentJobsJobIdRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsIndexRoute
  '/student/jobs': typeof AuthenticatedStudentJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/contact': typeof ContactRoute
  '/find-passion': typeof FindPassionRoute
  '/graduates': typeof GraduatesRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/candidates/browse': typeof CandidatesBrowseRoute
  '/candidates/features': typeof CandidatesFeaturesRoute
  '/candidates/recruiter-dashboard': typeof CandidatesRecruiterDashboardRoute
  '/graduates/cv-analyzer': typeof GraduatesCvAnalyzerRoute
  '/graduates/messaging': typeof GraduatesMessagingRoute
  '/graduates/profile': typeof GraduatesProfileRoute
  '/news/$slug': typeof NewsSlugRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/graduates/': typeof GraduatesIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/_authenticated/employer/cv-board': typeof AuthenticatedEmployerCvBoardRoute
  '/_authenticated/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/_authenticated/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/_authenticated/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/_authenticated/student/cv-analyzer': typeof AuthenticatedStudentCvAnalyzerRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/job-map': typeof AuthenticatedStudentJobMapRoute
  '/_authenticated/student/learn': typeof AuthenticatedStudentLearnRoute
  '/_authenticated/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/_authenticated/student/my-cv': typeof AuthenticatedStudentMyCvRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/_authenticated/student/jobs/$jobId': typeof AuthenticatedStudentJobsJobIdRoute
  '/_authenticated/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/_authenticated/student/jobs/': typeof AuthenticatedStudentJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/contact'
    | '/find-passion'
    | '/graduates'
    | '/news'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/employer'
    | '/profile'
    | '/student'
    | '/unauthorized'
    | '/candidates/browse'
    | '/candidates/features'
    | '/candidates/recruiter-dashboard'
    | '/graduates/cv-analyzer'
    | '/graduates/messaging'
    | '/graduates/profile'
    | '/news/$slug'
    | '/candidates/'
    | '/graduates/'
    | '/admin/dashboard'
    | '/admin/news'
    | '/employer/applications'
    | '/employer/cv-board'
    | '/employer/dashboard'
    | '/employer/messages'
    | '/student/applications'
    | '/student/cv-analyzer'
    | '/student/dashboard'
    | '/student/job-map'
    | '/student/learn'
    | '/student/messages'
    | '/student/my-cv'
    | '/admin/'
    | '/employer/'
    | '/student/'
    | '/employer/jobs/new'
    | '/student/jobs/$jobId'
    | '/employer/jobs/'
    | '/student/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/find-passion'
    | '/news'
    | '/sitemap.xml'
    | '/dashboard'
    | '/profile'
    | '/unauthorized'
    | '/candidates/browse'
    | '/candidates/features'
    | '/candidates/recruiter-dashboard'
    | '/graduates/cv-analyzer'
    | '/graduates/messaging'
    | '/graduates/profile'
    | '/news/$slug'
    | '/candidates'
    | '/graduates'
    | '/admin/dashboard'
    | '/admin/news'
    | '/employer/applications'
    | '/employer/cv-board'
    | '/employer/dashboard'
    | '/employer/messages'
    | '/student/applications'
    | '/student/cv-analyzer'
    | '/student/dashboard'
    | '/student/job-map'
    | '/student/learn'
    | '/student/messages'
    | '/student/my-cv'
    | '/admin'
    | '/employer'
    | '/student'
    | '/employer/jobs/new'
    | '/student/jobs/$jobId'
    | '/employer/jobs'
    | '/student/jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/contact'
    | '/find-passion'
    | '/graduates'
    | '/news'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/employer'
    | '/_authenticated/profile'
    | '/_authenticated/student'
    | '/_authenticated/unauthorized'
    | '/candidates/browse'
    | '/candidates/features'
    | '/candidates/recruiter-dashboard'
    | '/graduates/cv-analyzer'
    | '/graduates/messaging'
    | '/graduates/profile'
    | '/news/$slug'
    | '/candidates/'
    | '/graduates/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/news'
    | '/_authenticated/employer/applications'
    | '/_authenticated/employer/cv-board'
    | '/_authenticated/employer/dashboard'
    | '/_authenticated/employer/messages'
    | '/_authenticated/student/applications'
    | '/_authenticated/student/cv-analyzer'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/job-map'
    | '/_authenticated/student/learn'
    | '/_authenticated/student/messages'
    | '/_authenticated/student/my-cv'
    | '/_authenticated/admin/'
    | '/_authenticated/employer/'
    | '/_authenticated/student/'
    | '/_authenticated/employer/jobs/new'
    | '/_authenticated/student/jobs/$jobId'
    | '/_authenticated/employer/jobs/'
    | '/_authenticated/student/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CandidatesRoute: typeof CandidatesRouteWithChildren
  ContactRoute: typeof ContactRoute
  FindPassionRoute: typeof FindPassionRoute
  GraduatesRoute: typeof GraduatesRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates': {
      id: '/graduates'
      path: '/graduates'
      fullPath: '/graduates'
      preLoaderRoute: typeof GraduatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-passion': {
      id: '/find-passion'
      path: '/find-passion'
      fullPath: '/find-passion'
      preLoaderRoute: typeof FindPassionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates/': {
      id: '/graduates/'
      path: '/'
      fullPath: '/graduates/'
      preLoaderRoute: typeof GraduatesIndexRouteImport
      parentRoute: typeof GraduatesRoute
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/graduates/profile': {
      id: '/graduates/profile'
      path: '/profile'
      fullPath: '/graduates/profile'
      preLoaderRoute: typeof GraduatesProfileRouteImport
      parentRoute: typeof GraduatesRoute
    }
    '/graduates/messaging': {
      id: '/graduates/messaging'
      path: '/messaging'
      fullPath: '/graduates/messaging'
      preLoaderRoute: typeof GraduatesMessagingRouteImport
      parentRoute: typeof GraduatesRoute
    }
    '/graduates/cv-analyzer': {
      id: '/graduates/cv-analyzer'
      path: '/cv-analyzer'
      fullPath: '/graduates/cv-analyzer'
      preLoaderRoute: typeof GraduatesCvAnalyzerRouteImport
      parentRoute: typeof GraduatesRoute
    }
    '/candidates/recruiter-dashboard': {
      id: '/candidates/recruiter-dashboard'
      path: '/recruiter-dashboard'
      fullPath: '/candidates/recruiter-dashboard'
      preLoaderRoute: typeof CandidatesRecruiterDashboardRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/candidates/features': {
      id: '/candidates/features'
      path: '/features'
      fullPath: '/candidates/features'
      preLoaderRoute: typeof CandidatesFeaturesRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/candidates/browse': {
      id: '/candidates/browse'
      path: '/browse'
      fullPath: '/candidates/browse'
      preLoaderRoute: typeof CandidatesBrowseRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/_authenticated/unauthorized': {
      id: '/_authenticated/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthenticatedUnauthorizedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/my-cv': {
      id: '/_authenticated/student/my-cv'
      path: '/my-cv'
      fullPath: '/student/my-cv'
      preLoaderRoute: typeof AuthenticatedStudentMyCvRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/messages': {
      id: '/_authenticated/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof AuthenticatedStudentMessagesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/learn': {
      id: '/_authenticated/student/learn'
      path: '/learn'
      fullPath: '/student/learn'
      preLoaderRoute: typeof AuthenticatedStudentLearnRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/job-map': {
      id: '/_authenticated/student/job-map'
      path: '/job-map'
      fullPath: '/student/job-map'
      preLoaderRoute: typeof AuthenticatedStudentJobMapRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/cv-analyzer': {
      id: '/_authenticated/student/cv-analyzer'
      path: '/cv-analyzer'
      fullPath: '/student/cv-analyzer'
      preLoaderRoute: typeof AuthenticatedStudentCvAnalyzerRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/applications': {
      id: '/_authenticated/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof AuthenticatedStudentApplicationsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/employer/messages': {
      id: '/_authenticated/employer/messages'
      path: '/messages'
      fullPath: '/employer/messages'
      preLoaderRoute: typeof AuthenticatedEmployerMessagesRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/dashboard': {
      id: '/_authenticated/employer/dashboard'
      path: '/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof AuthenticatedEmployerDashboardRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/cv-board': {
      id: '/_authenticated/employer/cv-board'
      path: '/cv-board'
      fullPath: '/employer/cv-board'
      preLoaderRoute: typeof AuthenticatedEmployerCvBoardRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/applications': {
      id: '/_authenticated/employer/applications'
      path: '/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof AuthenticatedEmployerApplicationsRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/jobs/': {
      id: '/_authenticated/student/jobs/'
      path: '/jobs'
      fullPath: '/student/jobs/'
      preLoaderRoute: typeof AuthenticatedStudentJobsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/employer/jobs/': {
      id: '/_authenticated/employer/jobs/'
      path: '/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof AuthenticatedEmployerJobsIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/student/jobs/$jobId': {
      id: '/_authenticated/student/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/student/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedStudentJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/employer/jobs/new': {
      id: '/_authenticated/employer/jobs/new'
      path: '/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof AuthenticatedEmployerJobsNewRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEmployerRouteChildren {
  AuthenticatedEmployerApplicationsRoute: typeof AuthenticatedEmployerApplicationsRoute
  AuthenticatedEmployerCvBoardRoute: typeof AuthenticatedEmployerCvBoardRoute
  AuthenticatedEmployerDashboardRoute: typeof AuthenticatedEmployerDashboardRoute
  AuthenticatedEmployerMessagesRoute: typeof AuthenticatedEmployerMessagesRoute
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
  AuthenticatedEmployerJobsNewRoute: typeof AuthenticatedEmployerJobsNewRoute
  AuthenticatedEmployerJobsIndexRoute: typeof AuthenticatedEmployerJobsIndexRoute
}

const AuthenticatedEmployerRouteChildren: AuthenticatedEmployerRouteChildren = {
  AuthenticatedEmployerApplicationsRoute:
    AuthenticatedEmployerApplicationsRoute,
  AuthenticatedEmployerCvBoardRoute: AuthenticatedEmployerCvBoardRoute,
  AuthenticatedEmployerDashboardRoute: AuthenticatedEmployerDashboardRoute,
  AuthenticatedEmployerMessagesRoute: AuthenticatedEmployerMessagesRoute,
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
  AuthenticatedEmployerJobsNewRoute: AuthenticatedEmployerJobsNewRoute,
  AuthenticatedEmployerJobsIndexRoute: AuthenticatedEmployerJobsIndexRoute,
}

const AuthenticatedEmployerRouteWithChildren =
  AuthenticatedEmployerRoute._addFileChildren(
    AuthenticatedEmployerRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentApplicationsRoute: typeof AuthenticatedStudentApplicationsRoute
  AuthenticatedStudentCvAnalyzerRoute: typeof AuthenticatedStudentCvAnalyzerRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentJobMapRoute: typeof AuthenticatedStudentJobMapRoute
  AuthenticatedStudentLearnRoute: typeof AuthenticatedStudentLearnRoute
  AuthenticatedStudentMessagesRoute: typeof AuthenticatedStudentMessagesRoute
  AuthenticatedStudentMyCvRoute: typeof AuthenticatedStudentMyCvRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentJobsJobIdRoute: typeof AuthenticatedStudentJobsJobIdRoute
  AuthenticatedStudentJobsIndexRoute: typeof AuthenticatedStudentJobsIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentApplicationsRoute: AuthenticatedStudentApplicationsRoute,
  AuthenticatedStudentCvAnalyzerRoute: AuthenticatedStudentCvAnalyzerRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentJobMapRoute: AuthenticatedStudentJobMapRoute,
  AuthenticatedStudentLearnRoute: AuthenticatedStudentLearnRoute,
  AuthenticatedStudentMessagesRoute: AuthenticatedStudentMessagesRoute,
  AuthenticatedStudentMyCvRoute: AuthenticatedStudentMyCvRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedStudentJobsJobIdRoute: AuthenticatedStudentJobsJobIdRoute,
  AuthenticatedStudentJobsIndexRoute: AuthenticatedStudentJobsIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedUnauthorizedRoute: typeof AuthenticatedUnauthorizedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedUnauthorizedRoute: AuthenticatedUnauthorizedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CandidatesRouteChildren {
  CandidatesBrowseRoute: typeof CandidatesBrowseRoute
  CandidatesFeaturesRoute: typeof CandidatesFeaturesRoute
  CandidatesRecruiterDashboardRoute: typeof CandidatesRecruiterDashboardRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
}

const CandidatesRouteChildren: CandidatesRouteChildren = {
  CandidatesBrowseRoute: CandidatesBrowseRoute,
  CandidatesFeaturesRoute: CandidatesFeaturesRoute,
  CandidatesRecruiterDashboardRoute: CandidatesRecruiterDashboardRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
}

const CandidatesRouteWithChildren = CandidatesRoute._addFileChildren(
  CandidatesRouteChildren,
)

interface GraduatesRouteChildren {
  GraduatesCvAnalyzerRoute: typeof GraduatesCvAnalyzerRoute
  GraduatesMessagingRoute: typeof GraduatesMessagingRoute
  GraduatesProfileRoute: typeof GraduatesProfileRoute
  GraduatesIndexRoute: typeof GraduatesIndexRoute
}

const GraduatesRouteChildren: GraduatesRouteChildren = {
  GraduatesCvAnalyzerRoute: GraduatesCvAnalyzerRoute,
  GraduatesMessagingRoute: GraduatesMessagingRoute,
  GraduatesProfileRoute: GraduatesProfileRoute,
  GraduatesIndexRoute: GraduatesIndexRoute,
}

const GraduatesRouteWithChildren = GraduatesRoute._addFileChildren(
  GraduatesRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CandidatesRoute: CandidatesRouteWithChildren,
  ContactRoute: ContactRoute,
  FindPassionRoute: FindPassionRoute,
  GraduatesRoute: GraduatesRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
