/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UndergraduateRouteImport } from './routes/undergraduate'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GraduatesRouteImport } from './routes/graduates'
import { Route as FindPassionRouteImport } from './routes/find-passion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStudentMyCvRouteImport } from './routes/_authenticated/student.my-cv'
import { Route as AuthenticatedStudentMessagesRouteImport } from './routes/_authenticated/student.messages'
import { Route as AuthenticatedStudentLearnRouteImport } from './routes/_authenticated/student.learn'
import { Route as AuthenticatedStudentJobMapRouteImport } from './routes/_authenticated/student.job-map'
import { Route as AuthenticatedStudentCvAnalyzerRouteImport } from './routes/_authenticated/student.cv-analyzer'
import { Route as AuthenticatedStudentApplicationsRouteImport } from './routes/_authenticated/student.applications'
import { Route as AuthenticatedEmployerCvBoardRouteImport } from './routes/_authenticated/employer.cv-board'
import { Route as AuthenticatedEmployerApplicationsRouteImport } from './routes/_authenticated/employer.applications'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedStudentLessonsIndexRouteImport } from './routes/_authenticated/student.lessons.index'
import { Route as AuthenticatedStudentJobsIndexRouteImport } from './routes/_authenticated/student.jobs.index'
import { Route as AuthenticatedEmployerJobsIndexRouteImport } from './routes/_authenticated/employer.jobs.index'
import { Route as AuthenticatedStudentLessonsLessonIdRouteImport } from './routes/_authenticated/student.lessons.$lessonId'
import { Route as AuthenticatedStudentJobsJobIdRouteImport } from './routes/_authenticated/student.jobs.$jobId'
import { Route as AuthenticatedEmployerJobsNewRouteImport } from './routes/_authenticated/employer.jobs.new'

const UndergraduateRoute = UndergraduateRouteImport.update({
  id: '/undergraduate',
  path: '/undergraduate',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesRoute = GraduatesRouteImport.update({
  id: '/graduates',
  path: '/graduates',
  getParentRoute: () => rootRouteImport,
} as any)
const FindPassionRoute = FindPassionRouteImport.update({
  id: '/find-passion',
  path: '/find-passion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentMyCvRoute =
  AuthenticatedStudentMyCvRouteImport.update({
    id: '/student/my-cv',
    path: '/student/my-cv',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentMessagesRoute =
  AuthenticatedStudentMessagesRouteImport.update({
    id: '/student/messages',
    path: '/student/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentLearnRoute =
  AuthenticatedStudentLearnRouteImport.update({
    id: '/student/learn',
    path: '/student/learn',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentJobMapRoute =
  AuthenticatedStudentJobMapRouteImport.update({
    id: '/student/job-map',
    path: '/student/job-map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCvAnalyzerRoute =
  AuthenticatedStudentCvAnalyzerRouteImport.update({
    id: '/student/cv-analyzer',
    path: '/student/cv-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentApplicationsRoute =
  AuthenticatedStudentApplicationsRouteImport.update({
    id: '/student/applications',
    path: '/student/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerCvBoardRoute =
  AuthenticatedEmployerCvBoardRouteImport.update({
    id: '/employer/cv-board',
    path: '/employer/cv-board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerApplicationsRoute =
  AuthenticatedEmployerApplicationsRouteImport.update({
    id: '/employer/applications',
    path: '/employer/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentLessonsIndexRoute =
  AuthenticatedStudentLessonsIndexRouteImport.update({
    id: '/student/lessons/',
    path: '/student/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentJobsIndexRoute =
  AuthenticatedStudentJobsIndexRouteImport.update({
    id: '/student/jobs/',
    path: '/student/jobs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsIndexRoute =
  AuthenticatedEmployerJobsIndexRouteImport.update({
    id: '/employer/jobs/',
    path: '/employer/jobs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentLessonsLessonIdRoute =
  AuthenticatedStudentLessonsLessonIdRouteImport.update({
    id: '/student/lessons/$lessonId',
    path: '/student/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentJobsJobIdRoute =
  AuthenticatedStudentJobsJobIdRouteImport.update({
    id: '/student/jobs/$jobId',
    path: '/student/jobs/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsNewRoute =
  AuthenticatedEmployerJobsNewRouteImport.update({
    id: '/employer/jobs/new',
    path: '/employer/jobs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/find-passion': typeof FindPassionRoute
  '/graduates': typeof GraduatesRoute
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/undergraduate': typeof UndergraduateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/employer/cv-board': typeof AuthenticatedEmployerCvBoardRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/cv-analyzer': typeof AuthenticatedStudentCvAnalyzerRoute
  '/student/job-map': typeof AuthenticatedStudentJobMapRoute
  '/student/learn': typeof AuthenticatedStudentLearnRoute
  '/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/student/my-cv': typeof AuthenticatedStudentMyCvRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/student/jobs/$jobId': typeof AuthenticatedStudentJobsJobIdRoute
  '/student/lessons/$lessonId': typeof AuthenticatedStudentLessonsLessonIdRoute
  '/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/student/jobs/': typeof AuthenticatedStudentJobsIndexRoute
  '/student/lessons/': typeof AuthenticatedStudentLessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/find-passion': typeof FindPassionRoute
  '/graduates': typeof GraduatesRoute
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/undergraduate': typeof UndergraduateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/employer/cv-board': typeof AuthenticatedEmployerCvBoardRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/cv-analyzer': typeof AuthenticatedStudentCvAnalyzerRoute
  '/student/job-map': typeof AuthenticatedStudentJobMapRoute
  '/student/learn': typeof AuthenticatedStudentLearnRoute
  '/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/student/my-cv': typeof AuthenticatedStudentMyCvRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/student/jobs/$jobId': typeof AuthenticatedStudentJobsJobIdRoute
  '/student/lessons/$lessonId': typeof AuthenticatedStudentLessonsLessonIdRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsIndexRoute
  '/student/jobs': typeof AuthenticatedStudentJobsIndexRoute
  '/student/lessons': typeof AuthenticatedStudentLessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/find-passion': typeof FindPassionRoute
  '/graduates': typeof GraduatesRoute
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/undergraduate': typeof UndergraduateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/news/$slug': typeof NewsSlugRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/_authenticated/employer/cv-board': typeof AuthenticatedEmployerCvBoardRoute
  '/_authenticated/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/_authenticated/student/cv-analyzer': typeof AuthenticatedStudentCvAnalyzerRoute
  '/_authenticated/student/job-map': typeof AuthenticatedStudentJobMapRoute
  '/_authenticated/student/learn': typeof AuthenticatedStudentLearnRoute
  '/_authenticated/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/_authenticated/student/my-cv': typeof AuthenticatedStudentMyCvRoute
  '/_authenticated/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/_authenticated/student/jobs/$jobId': typeof AuthenticatedStudentJobsJobIdRoute
  '/_authenticated/student/lessons/$lessonId': typeof AuthenticatedStudentLessonsLessonIdRoute
  '/_authenticated/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/_authenticated/student/jobs/': typeof AuthenticatedStudentJobsIndexRoute
  '/_authenticated/student/lessons/': typeof AuthenticatedStudentLessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/contact'
    | '/find-passion'
    | '/graduates'
    | '/news'
    | '/sitemap.xml'
    | '/undergraduate'
    | '/dashboard'
    | '/profile'
    | '/news/$slug'
    | '/admin/news'
    | '/employer/applications'
    | '/employer/cv-board'
    | '/student/applications'
    | '/student/cv-analyzer'
    | '/student/job-map'
    | '/student/learn'
    | '/student/messages'
    | '/student/my-cv'
    | '/employer/jobs/new'
    | '/student/jobs/$jobId'
    | '/student/lessons/$lessonId'
    | '/employer/jobs/'
    | '/student/jobs/'
    | '/student/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/contact'
    | '/find-passion'
    | '/graduates'
    | '/news'
    | '/sitemap.xml'
    | '/undergraduate'
    | '/dashboard'
    | '/profile'
    | '/news/$slug'
    | '/admin/news'
    | '/employer/applications'
    | '/employer/cv-board'
    | '/student/applications'
    | '/student/cv-analyzer'
    | '/student/job-map'
    | '/student/learn'
    | '/student/messages'
    | '/student/my-cv'
    | '/employer/jobs/new'
    | '/student/jobs/$jobId'
    | '/student/lessons/$lessonId'
    | '/employer/jobs'
    | '/student/jobs'
    | '/student/lessons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/contact'
    | '/find-passion'
    | '/graduates'
    | '/news'
    | '/sitemap.xml'
    | '/undergraduate'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/news/$slug'
    | '/_authenticated/admin/news'
    | '/_authenticated/employer/applications'
    | '/_authenticated/employer/cv-board'
    | '/_authenticated/student/applications'
    | '/_authenticated/student/cv-analyzer'
    | '/_authenticated/student/job-map'
    | '/_authenticated/student/learn'
    | '/_authenticated/student/messages'
    | '/_authenticated/student/my-cv'
    | '/_authenticated/employer/jobs/new'
    | '/_authenticated/student/jobs/$jobId'
    | '/_authenticated/student/lessons/$lessonId'
    | '/_authenticated/employer/jobs/'
    | '/_authenticated/student/jobs/'
    | '/_authenticated/student/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CandidatesRoute: typeof CandidatesRoute
  ContactRoute: typeof ContactRoute
  FindPassionRoute: typeof FindPassionRoute
  GraduatesRoute: typeof GraduatesRoute
  NewsRoute: typeof NewsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UndergraduateRoute: typeof UndergraduateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/undergraduate': {
      id: '/undergraduate'
      path: '/undergraduate'
      fullPath: '/undergraduate'
      preLoaderRoute: typeof UndergraduateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates': {
      id: '/graduates'
      path: '/graduates'
      fullPath: '/graduates'
      preLoaderRoute: typeof GraduatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-passion': {
      id: '/find-passion'
      path: '/find-passion'
      fullPath: '/find-passion'
      preLoaderRoute: typeof FindPassionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/my-cv': {
      id: '/_authenticated/student/my-cv'
      path: '/student/my-cv'
      fullPath: '/student/my-cv'
      preLoaderRoute: typeof AuthenticatedStudentMyCvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/messages': {
      id: '/_authenticated/student/messages'
      path: '/student/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof AuthenticatedStudentMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/learn': {
      id: '/_authenticated/student/learn'
      path: '/student/learn'
      fullPath: '/student/learn'
      preLoaderRoute: typeof AuthenticatedStudentLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/job-map': {
      id: '/_authenticated/student/job-map'
      path: '/student/job-map'
      fullPath: '/student/job-map'
      preLoaderRoute: typeof AuthenticatedStudentJobMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/cv-analyzer': {
      id: '/_authenticated/student/cv-analyzer'
      path: '/student/cv-analyzer'
      fullPath: '/student/cv-analyzer'
      preLoaderRoute: typeof AuthenticatedStudentCvAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/applications': {
      id: '/_authenticated/student/applications'
      path: '/student/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof AuthenticatedStudentApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/cv-board': {
      id: '/_authenticated/employer/cv-board'
      path: '/employer/cv-board'
      fullPath: '/employer/cv-board'
      preLoaderRoute: typeof AuthenticatedEmployerCvBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/applications': {
      id: '/_authenticated/employer/applications'
      path: '/employer/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof AuthenticatedEmployerApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/lessons/': {
      id: '/_authenticated/student/lessons/'
      path: '/student/lessons'
      fullPath: '/student/lessons/'
      preLoaderRoute: typeof AuthenticatedStudentLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/jobs/': {
      id: '/_authenticated/student/jobs/'
      path: '/student/jobs'
      fullPath: '/student/jobs/'
      preLoaderRoute: typeof AuthenticatedStudentJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs/': {
      id: '/_authenticated/employer/jobs/'
      path: '/employer/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof AuthenticatedEmployerJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/lessons/$lessonId': {
      id: '/_authenticated/student/lessons/$lessonId'
      path: '/student/lessons/$lessonId'
      fullPath: '/student/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/jobs/$jobId': {
      id: '/_authenticated/student/jobs/$jobId'
      path: '/student/jobs/$jobId'
      fullPath: '/student/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedStudentJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs/new': {
      id: '/_authenticated/employer/jobs/new'
      path: '/employer/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof AuthenticatedEmployerJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedEmployerApplicationsRoute: typeof AuthenticatedEmployerApplicationsRoute
  AuthenticatedEmployerCvBoardRoute: typeof AuthenticatedEmployerCvBoardRoute
  AuthenticatedStudentApplicationsRoute: typeof AuthenticatedStudentApplicationsRoute
  AuthenticatedStudentCvAnalyzerRoute: typeof AuthenticatedStudentCvAnalyzerRoute
  AuthenticatedStudentJobMapRoute: typeof AuthenticatedStudentJobMapRoute
  AuthenticatedStudentLearnRoute: typeof AuthenticatedStudentLearnRoute
  AuthenticatedStudentMessagesRoute: typeof AuthenticatedStudentMessagesRoute
  AuthenticatedStudentMyCvRoute: typeof AuthenticatedStudentMyCvRoute
  AuthenticatedEmployerJobsNewRoute: typeof AuthenticatedEmployerJobsNewRoute
  AuthenticatedStudentJobsJobIdRoute: typeof AuthenticatedStudentJobsJobIdRoute
  AuthenticatedStudentLessonsLessonIdRoute: typeof AuthenticatedStudentLessonsLessonIdRoute
  AuthenticatedEmployerJobsIndexRoute: typeof AuthenticatedEmployerJobsIndexRoute
  AuthenticatedStudentJobsIndexRoute: typeof AuthenticatedStudentJobsIndexRoute
  AuthenticatedStudentLessonsIndexRoute: typeof AuthenticatedStudentLessonsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedEmployerApplicationsRoute:
    AuthenticatedEmployerApplicationsRoute,
  AuthenticatedEmployerCvBoardRoute: AuthenticatedEmployerCvBoardRoute,
  AuthenticatedStudentApplicationsRoute: AuthenticatedStudentApplicationsRoute,
  AuthenticatedStudentCvAnalyzerRoute: AuthenticatedStudentCvAnalyzerRoute,
  AuthenticatedStudentJobMapRoute: AuthenticatedStudentJobMapRoute,
  AuthenticatedStudentLearnRoute: AuthenticatedStudentLearnRoute,
  AuthenticatedStudentMessagesRoute: AuthenticatedStudentMessagesRoute,
  AuthenticatedStudentMyCvRoute: AuthenticatedStudentMyCvRoute,
  AuthenticatedEmployerJobsNewRoute: AuthenticatedEmployerJobsNewRoute,
  AuthenticatedStudentJobsJobIdRoute: AuthenticatedStudentJobsJobIdRoute,
  AuthenticatedStudentLessonsLessonIdRoute:
    AuthenticatedStudentLessonsLessonIdRoute,
  AuthenticatedEmployerJobsIndexRoute: AuthenticatedEmployerJobsIndexRoute,
  AuthenticatedStudentJobsIndexRoute: AuthenticatedStudentJobsIndexRoute,
  AuthenticatedStudentLessonsIndexRoute: AuthenticatedStudentLessonsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CandidatesRoute: CandidatesRoute,
  ContactRoute: ContactRoute,
  FindPassionRoute: FindPassionRoute,
  GraduatesRoute: GraduatesRoute,
  NewsRoute: NewsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UndergraduateRoute: UndergraduateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
